version: '3.2'

services:  
  nginx:
    image: nginx:1.25.4-bookworm
    build: .
    volumes:
      - /media/ngonzalez/Samsung_T5:/tmp/media/Samsung_T5
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    command: nginx -g "daemon off;"
